Repository Brightscout/mattermost-plugin-msteams-sync, pull requests merged in 2023-12, with the labels that each got.

#37 [MI-3827]: RTL base setup + downgrade to react 17
  .gitignore
  webapp/babel.config.js
  webapp/jest.config.ts
  webapp/package.json
  webapp/src/containers/Rhs/views/ConnectAccount/ConnectAccount.test.tsx
  webapp/src/containers/Rhs/views/ConnectAccount/__snapshots__/ConnectAccount.test.tsx.snap
  webapp/src/tests/i18n_mock.json
  webapp/src/tests/mockState.ts
  webapp/src/tests/setup.ts
  webapp/yarn.lock
Labels: Phase-1

#44 [MI-3835] Add logic to hide/show RHS on the basis of system console setting
  plugin.json
  server/api.go
  server/api_test.go
  server/configuration.go
  webapp/src/App.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/__snapshots__/LinkedChannelCard.test.tsx.snap
  webapp/src/components/RhsTitle/RhsTitle.component.tsx
  webapp/src/components/RhsTitle/__snapshots__/RhsTitle.test.tsx.snap
  webapp/src/components/Snackbar/Snackbar.component.tsx
  webapp/src/components/Snackbar/Snackbar.test.tsx
  webapp/src/components/Snackbar/__snapshots__/Snackbar.test.tsx.snap
  webapp/src/constants/apiService.constant.ts
  webapp/src/constants/common.constants.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/containers/Rhs/__snapshots__/Rhs.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectAccount/ConnectAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectAccount/__snapshots__/ConnectAccount.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectedAccount/ConnectedAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/__snapshots__/ConnectedAccount.test.tsx.snap
  webapp/src/containers/Rhs/views/LinkedChannels/LinkedChannels.container.tsx
  webapp/src/containers/Rhs/views/LinkedChannels/__snapshots__/LinkedChannels.test.tsx.snap
  webapp/src/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_utils.scss
  webapp/src/types/common/index.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/types/mattermost-webapp/index.d.ts
Labels: Phase-1

#48 [MI-3841] Review fixes for Phase 1 UI PR related to backend
  server/api.go
  server/api_test.go
  server/store/storemodels/storemodels.go
Labels: Phase-1

#46 [MI-3836] Integrate API to unlink channels and websocket event
  server/api.go
  webapp/src/components/Dialog/Dialog.component.tsx
  webapp/src/components/LinkChannelModal/LinkChannelModal.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.types.ts
  webapp/src/components/index.ts
  webapp/src/constants/apiService.constant.ts
  webapp/src/constants/common.constants.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/hooks/useDialog.tsx
  webapp/src/index.tsx
  webapp/src/reducers/dialog/index.ts
  webapp/src/reducers/index.ts
  webapp/src/reducers/linkModal/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_variables.scss
  webapp/src/types/common/payload.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/websocket/index.ts
Labels: Phase-3

#47 [MI-3837]: Integrate webhooks and enhancements
  webapp/src/components/LinkChannelModal/LinkChannelModal.component.tsx
  webapp/src/components/LinkChannelModal/SearchMMChannels/SearchMMChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSChannels/SearchMSChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSTeams/SearchMSTeams.component.tsx
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/index.tsx
  webapp/src/reducers/linkModal/index.ts
  webapp/src/types/common/store.d.ts
  webapp/src/websocket/index.ts
Labels: Phase-3

#49 [MI-3828] Review fixes for Phase 2 UI given by QA
  server/api.go
  webapp/src/components/WarningCard/WarningCard.component.tsx
  webapp/src/components/WarningCard/__snapshots__/WarningCard.test.tsx.snap
  webapp/src/constants/linkedChannels.constants.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
Labels: Phase-2

#45 [MI-3834] Add unlink button on hover state on linked channel list
  server/api.go
  webapp/src/components/Dialog/Dialog.component.tsx
  webapp/src/components/Icon/Icon.map.tsx
  webapp/src/components/LinkChannelModal/LinkChannelModal.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.styles.scss
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.types.ts
  webapp/src/components/index.ts
  webapp/src/constants/apiService.constant.ts
  webapp/src/constants/common.constants.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/hooks/useDialog.tsx
  webapp/src/index.tsx
  webapp/src/reducers/dialog/index.ts
  webapp/src/reducers/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_variables.scss
  webapp/src/types/common/payload.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/websocket/index.ts
Labels: Phase-3

#50 [MI-3842]: Review fixes frontend phase 1
  webapp/__mocks__/svg.js
  webapp/jest.config.ts
  webapp/src/App.tsx
  webapp/src/components/Dialog/Dialog.component.tsx
  webapp/src/components/Dialog/Dialog.test.tsx
  webapp/src/components/Dialog/__snapshots__/Dialog.test.tsx.snap
  webapp/src/components/Snackbar/Snackbar.component.tsx
  webapp/src/components/enforceConnectedAccountModal.tsx
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/containers/Rhs/__snapshots__/Rhs.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectAccount/ConnectAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/ConnectedAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/ConnectedAccount.test.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/__snapshots__/ConnectedAccount.test.tsx.snap
  webapp/src/containers/Rhs/views/LinkedChannels/LinkedChannels.container.tsx
  webapp/src/hooks/useAlert.ts
  webapp/src/hooks/useApiRequestCompletionState.ts
  webapp/src/hooks/useDialog.tsx
  webapp/src/hooks/usePluginApi.ts
  webapp/src/index.tsx
  webapp/src/reducers/dialog/index.test.ts
  webapp/src/reducers/dialog/index.ts
  webapp/src/reducers/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_variables.scss
  webapp/src/types/common/store.d.ts
  webapp/src/utils/index.ts
Labels: Phase-1

#43 [MI-3833]: Link channel modal integration
  server/api.go
  webapp/src/components/Dialog/Dialog.component.tsx
  webapp/src/components/Icon/Icon.map.tsx
  webapp/src/components/LinkChannelModal/LinkChannelModal.component.tsx
  webapp/src/components/LinkChannelModal/SearchMMChannels/SearchMMChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSChannels/SearchMSChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSTeams/SearchMSTeams.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.styles.scss
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.types.ts
  webapp/src/components/index.ts
  webapp/src/constants/apiService.constant.ts
  webapp/src/constants/common.constants.ts
  webapp/src/constants/index.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/containers/Rhs/Rhs.styles.scss
  webapp/src/hooks/useDialog.tsx
  webapp/src/index.tsx
  webapp/src/reducers/dialog/index.ts
  webapp/src/reducers/index.ts
  webapp/src/reducers/linkModal/index.ts
  webapp/src/reducers/refetchState/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_variables.scss
  webapp/src/types/common/payload.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/websocket/index.ts
Labels: Phase-3

#41 [MI-3828] Add feature to show linked channels and search the linked channels
  server/api.go
  webapp/src/App.tsx
  webapp/src/components/Icon/Icon.map.tsx
  webapp/src/components/Icon/Icon.types.ts
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.styles.scss
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.test.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.types.ts
  webapp/src/components/LinkedChannelCard/__snapshots__/LinkedChannelCard.test.tsx.snap
  webapp/src/components/WarningCard/WarningCard.component.tsx
  webapp/src/components/WarningCard/__snapshots__/WarningCard.test.tsx.snap
  webapp/src/components/enforceConnectedAccountModal.tsx
  webapp/src/constants/common.constants.ts
  webapp/src/constants/linkedChannels.constants.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/containers/Rhs/Rhs.styles.scss
  webapp/src/containers/Rhs/Rhs.test.tsx
  webapp/src/containers/Rhs/__snapshots__/Rhs.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectAccount/ConnectAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectAccount/ConnectAccount.test.tsx
  webapp/src/containers/Rhs/views/ConnectAccount/__snapshots__/ConnectAccount.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectAccount/index.ts
  webapp/src/containers/Rhs/views/ConnectedAccount/ConnectedAccount.container.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/ConnectedAccount.test.tsx
  webapp/src/containers/Rhs/views/ConnectedAccount/__snapshots__/ConnectedAccount.test.tsx.snap
  webapp/src/containers/Rhs/views/ConnectedAccount/index.ts
  webapp/src/containers/Rhs/views/LinkedChannels/LinkedChannels.container.tsx
  webapp/src/containers/Rhs/views/LinkedChannels/LinkedChannels.mock.ts
  webapp/src/containers/Rhs/views/LinkedChannels/LinkedChannels.test.tsx
  webapp/src/containers/Rhs/views/LinkedChannels/__snapshots__/LinkedChannels.test.tsx.snap
  webapp/src/containers/Rhs/views/LinkedChannels/index.ts
  webapp/src/hooks/usePreviousState.ts
  webapp/src/styles/_utils.scss
Labels: Phase-2

#40 [MI-3831]: Link channels modal
  server/api.go
  webapp/package.json
  webapp/src/components/Dialog/Dialog.component.tsx
  webapp/src/components/Icon/Icon.map.tsx
  webapp/src/components/Icon/Icon.types.ts
  webapp/src/components/LinkChannelModal/LinkChannelModal.component.tsx
  webapp/src/components/LinkChannelModal/SearchMMChannels/SearchMMChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMMChannels/SearchMMChannels.types.ts
  webapp/src/components/LinkChannelModal/SearchMMChannels/index.ts
  webapp/src/components/LinkChannelModal/SearchMSChannels/SearchMSChannels.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSChannels/SearchMSChannels.types.ts
  webapp/src/components/LinkChannelModal/SearchMSChannels/index.ts
  webapp/src/components/LinkChannelModal/SearchMSTeams/SearchMSTeams.component.tsx
  webapp/src/components/LinkChannelModal/SearchMSTeams/index.ts
  webapp/src/components/LinkChannelModal/index.ts
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.component.tsx
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.styles.scss
  webapp/src/components/LinkedChannelCard/LinkedChannelCard.types.ts
  webapp/src/components/index.ts
  webapp/src/constants/apiService.constant.ts
  webapp/src/constants/common.constants.ts
  webapp/src/constants/index.ts
  webapp/src/containers/Rhs/Rhs.container.tsx
  webapp/src/containers/Rhs/Rhs.styles.scss
  webapp/src/hooks/useDialog.tsx
  webapp/src/index.tsx
  webapp/src/reducers/dialog/index.ts
  webapp/src/reducers/index.ts
  webapp/src/reducers/linkModal/index.ts
  webapp/src/reducers/refetchState/index.ts
  webapp/src/selectors/index.tsx
  webapp/src/services/index.ts
  webapp/src/styles/_utils.scss
  webapp/src/styles/_variables.scss
  webapp/src/types/common/index.d.ts
  webapp/src/types/common/payload.d.ts
  webapp/src/types/common/service.d.ts
  webapp/src/types/common/store.d.ts
  webapp/src/utils/index.ts
  webapp/src/websocket/index.ts
  webapp/yarn.lock
Labels: Phase-3
